version: "3"

services:
  keradmin:
    image: yinshengphy/keradmin
    container_name: keradmin
    hostname: keradmin
    ports:
      - 88:88
      - 749:749
    volumes:
      - keytab:/etc/security/keytab

  namenode:
    build: namenode
    container_name: namenode
    hostname: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - keytab:/etc/security/keytab
    env_file:
      - ./hadoop.env

  datanode:
    build: datanode
    volumes:
      - keytab:/etc/security/keytab
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  resourcemanager:
    build: resourcemanager
    hostname: resourcemanager
    ports:
      - 8088:8088
    volumes:
      - keytab:/etc/security/keytab
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env

  nodemanager:
    build: nodemanager
    hostname: nodemanager
    volumes:
      - keytab:/etc/security/keytab
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env

  historyserver:
    build: historyserver
    container_name: historyserver
    hostname: historyserver
    ports:
      - 8188:8188
    depends_on:
      - resourcemanager
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - keytab:/etc/security/keytab
    env_file:
      - ./hadoop.env

volumes:
  keytab:
  hadoop_namenode:
  hadoop_historyserver:
