version: "3"

services:
  namenode:
    build: namenode
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop.env

  datanode1:
    build: datanode
    container_name: datanode1
    hostname: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  datanode2:
    build: datanode
    container_name: datanode2
    hostname: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  datanode3:
    build: datanode
    container_name: datanode3
    hostname: datanode3
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
  resourcemanager:
    build: resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env

  nodemanager1:
    build: nodemanager
    container_name: nodemanager1
    hostname: nodemanager1
    restart: always
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env

  nodemanager2:
    build: nodemanager
    container_name: nodemanager2
    hostname: nodemanager2
    restart: always
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env

  nodemanager3:
    build: nodemanager
    container_name: nodemanager3
    hostname: nodemanager3
    restart: always
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env
  historyserver:
    build: historyserver
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - 8188:8188
    depends_on:
      - resourcemanager
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
